package spring.boot.security.jwt.controller;

import java.security.Principal;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import spring.boot.security.jwt.model.User;
import spring.boot.security.jwt.model.UserRequest;
import spring.boot.security.jwt.model.UserResponse;
import spring.boot.security.jwt.service.IUserService;
import spring.boot.security.jwt.util.JwtUtil;


@RestController
//@RequestMapping("/user")
public class UserController {
	
	//private static final Logger logger = LoggerFactory.getLogger(UserController.class);
	@Autowired
	private IUserService service; //HAS-A
	
	@Autowired
	private JwtUtil util;
	
	@Autowired
	private AuthenticationManager authenticationManager;
	
	//1. save User data in database
	@PostMapping("/save")
	public ResponseEntity<String> saveUser(
			@RequestBody User user) 
	{
		System.out.println("Inside");
		//logger.debug("inside UserController saveUser() method");
		Integer id  = service.saveUser(user);
		String body = "User '"+id+"' saved";
		//return new ResponseEntity<String>(body,HttpStatus.OK);
		return ResponseEntity.ok(body);
	}
	
	//2. Validate user and generate token(login)
	@PostMapping("/login")
	public ResponseEntity<UserResponse> loginUser(
			@RequestBody UserRequest request)
	{
		// validate un/pwd with database
		authenticationManager.authenticate(
				new UsernamePasswordAuthenticationToken(
						request.getUsername(), request.getPassword()));
		
		String token = util.generateToken(request.getUsername());
		return ResponseEntity.ok(
				new UserResponse(token,"Success! Generated By NIT-RAGHU")
				);
	}
	
	
	//3. after login only
	@PostMapping("/welcome")
	public ResponseEntity<String> accessData(Principal p)
	{
		return ResponseEntity.ok("Hello User!"+ p.getName());
	}
	@GetMapping("/sam")
	public ResponseEntity<String> sample()
	{
		System.out.println("Sample method");
		return ResponseEntity.ok("Hello User!");
	}
	
	
	
}
